### PR TITLE
Bump 2.7.0

### PR DESCRIPTION
**Pull request by haasad**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by haasad** [comment]
@conda-forge-admin, please rerender

**Comment by haasad** [comment]
closing because I made a fork in the LCA-ActivityBrowser organization and orgs apparently don't work

**Comment by m-rossi** [comment]
@haasad if you create a new release for your project the conda-forge bot should create a PR.

**Comment by haasad** [comment]
I'm aware of that, but it didn't happen after 12+ hours, so I'm making one manually now :man_shrugging:

**Comment by m-rossi** [comment]
Ok that's weird. I'm sorry I thought I turned on notifications for the activity-browser repo (what I normally do for packages I maintain recipes for). However it seems I forgot that for activity-browser.

**Pull request closed without merging**
